# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6289e660d4ad25f97a3194a2722858bef3c4e9d5a332426fa2d176889d36a19f975b5badb53d62285a90889e6d7f843f4bc4c4c406910964b921e3ccfd636914
  pag_seguro_email: rodrigotnoronha@outlook.com
  pag_seguro_token: 19A7CA757C2D4857A079CBEF9A7A20EB
  s3_access_key_id: AKIAJBYHTCMXQTSSLXFQ
  s3_secret_access_key: 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
  ecej_admin_password: ecej2016
  ecej_admin_password_confirmation: ecej2016
test:
  secret_key_base: 6289e660d4ad25f97a3194a2722858bef3c4e9d5a332426fa2d176889d36a19f975b5badb53d62285a90889e6d7f843f4bc4c4c406910964b921e3ccfd636914
  pag_seguro_email: rodrigotnoronha@outlook.com
  pag_seguro_token: 19A7CA757C2D4857A079CBEF9A7A20EB
  s3_access_key_id: AKIAJBYHTCMXQTSSLXFQ
  s3_secret_access_key: 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
  ecej_admin_password: ecej2016
  ecej_admin_password_confirmation: ecej2016
  # Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  pag_seguro_email: <%= ENV["PAGSEGURO_EMAIL"] %>
  pag_seguro_token: <%= ENV["PAGSEGURO_TOKEN"] %>
  s3_access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] %>
  s3_secret_access_key: <%= ENV["S3_SECRET_ACCESS_KEY"] %>
  ecej_admin_password: <%= ENV['ADMIN_PW'] %>
  ecej_admin_password_confirmation: <%= ENV['ADMIN_PW'] %>
