# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6289e660d4ad25f97a3194a2722858bef3c4e9d5a332426fa2d176889d36a19f975b5badb53d62285a90889e6d7f843f4bc4c4c406910964b921e3ccfd636914
  pag_seguro_email: rodrigotnoronha@outlook.com
  pag_seguro_token: 19A7CA757C2D4857A079CBEF9A7A20EB
test:
  secret_key_base: a901e6cf4d186e65163ec3dffbe4c8a9071b2ddd5e809679066fe78e8312bd47ede526b93243ee7a15fd39f44e78f46e9a5a6d0fa15a4cae9ef6f44d7d7f6276

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
